function clothoid_chain = init()

    addpath(fullfile('external', 'structprompt', 'gedit'));

    h = axes('NextPlot', 'Add', ...
             'DataAspectRatio', [1, 1, 1]);

    clothoid_chain = ...
        nodes.Clothoid(h, 0, 0, 0, 0, 'Length', 10, 'HeadingChange', 0). ...
        append('FinalCurvature', 1 / 10, 'HeadingChange', pi / 6). ...
        append('FinalCurvature', 1 / 10, 'HeadingChange', pi / 6). ...
        append('FinalCurvature', 0, 'HeadingChange', pi / 6). ...
        append('FinalCurvature', 0, 'Length', 5). ...
        append('FinalCurvature', 1 / 10, 'HeadingChange', pi / 2). ...
        append('FinalCurvature', 1 / 10, 'HeadingChange', pi / 4). ...
        append('FinalCurvature', 0, 'HeadingChange', pi / 4). ...
        chain();

end
